version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
    # If you want to run the backend, uncomment the above lines and specify the dependencies.

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongodb

  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"          # Jenkins UI
      - "50000:50000"        # For Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 Give Jenkins access to host Docker

volumes:
  # mongodb_data:
  jenkins_home: